name: sahabatqu
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^6.1.2
  dio: ^3.0.10
  provider: ^4.3.2+3
  cached_network_image: ^2.4.1
  carousel_slider: ^2.3.1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0
  fluttertoast: ^7.1.5
  geolocator: ^6.2.1
  geocoding: ^1.0.5
  google_maps_flutter: ^0.5.25+3
  google_maps_webservice: ^0.0.16
  lottie: ^0.7.0
  photo_view: ^0.10.2
  progress_dialog: ^1.2.1
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  intl: ^0.16.0
  flutter_qiblah: ^1.0.3+2
  curved_navigation_bar: ^0.3.7
  flutter_svg: ^0.21.0
  hijri: ^2.0.3
  url_launcher: ^5.4.2
  hijri_picker: ^2.0.0
  rxdart: ^0.24.1
  flutter_staggered_grid_view: ^0.3.4
  flutter_webview_plugin: ^0.3.11
  flutter_local_notifications: ^1.4.4+2
  expand_widget: ^1.2.0+1
  youtube_player_flutter: ^7.0.0+7
  another_flushbar: ^1.10.28

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.9.0

flutter_icons:
  image_path: "assets/logo_sahabat.png"
  android: true
  ios: true
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
