name: sahabatqu
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  flutter_bloc: ^8.0.1
  dio: ^4.0.6
  provider: ^6.0.2
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  firebase_messaging: ^14.1.2
  firebase_core: ^2.3.0
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  google_maps_flutter: ^2.1.3
  google_maps_webservice: ^0.0.20-nullsafety.5
  lottie: ^2.1.0
  photo_view: ^0.14.0
  shared_preferences: ^2.0.13
  shimmer: ^2.0.0
  intl: ^0.18.0
  flutter_qiblah: ^2.1.0
  curved_navigation_bar: ^1.0.3
  flutter_svg: ^1.0.3
  hijri: ^3.0.0
  url_launcher: ^6.0.20
  hijri_picker: ^3.0.0
  rxdart: ^0.27.3
  flutter_staggered_grid_view: ^0.6.1
  flutter_inappwebview: ^5.5.0+2
  flutter_local_notifications: ^13.0.0
  expand_widget: ^3.1.0
  youtube_player_flutter: ^8.0.0
  another_flushbar: ^1.12.29
  get_it: ^7.2.0

  about:
    path: about

  core:
    path: core

  schedule:
    path: schedule

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_launcher_icons: ^0.9.0

dependency_overrides:
  firebase_messaging_platform_interface: 4.2.10

flutter_icons:
  image_path: "assets/logo_sahabat.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-SemiBold.ttf
